services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=#
      - POSTGRES_PASSWORD=#
      - STRIPE_SECRET_KEY=#
      - STRIPE_PUBLIC_KEY=#
      - STRIPE_WEBHOOK_SECRET=#
      - NOVAPOST_API_KEY=#
      - GOOGLE_API_KEY=#
      - APP_UPLOAD_DIR=#
      - SPRING_REDIS_HOST= redis
      - SPRING_REDIS_PORT= #
    volumes:
      - #
    networks:
      - spring-postgres

  redis:
   image: redis:7
   ports:
    - #
   networks:
    - spring-postgres
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=#
      - POSTGRES_PASSWORD=#
    expose:
      - #
volumes:
  db-data:
  uploads:
networks:
  spring-postgres:
