spring.application.name=demo

spring.datasource.url = jdbc:postgresql://db:5432/#
spring.datasource.username = #
spring.datasource.password = #
spring.datasource.driver-class-name=org.postgresql.Driver

# update - update the database schema on startup
# create - creates the database schema on startup, destroying previous data
# create-drop - creates the database schema on startup and drops it on shutdown
# validate - validates the database schema, makes no changes to the database
# none - does nothing with the database schema
spring.jpa.hibernate.ddl-auto=create

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.encoding=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.data.redis.host=redis
spring.data.redis.port=#

stripe.secret.key =${STRIPE_SECRET_KEY}
stripe.public.key = ${STRIPE_PUBLIC_KEY}
stripe.webhook.secret = ${STRIPE_WEBHOOK_SECRET}

google.maps.api.key =#

novapost.api.key = ${NOVAPOST_API_KEY}
novapost.api.url = https://api.novaposhta.ua/v2.0/json/

app.domain = https://overweak-zaire-vaunted.ngrok-free.dev
app.upload.dir=${APP_UPLOAD_DIR}
app.delete.dir=/app/

# Налаштування для HTTP клієнта
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = #
spring.mail.password = #
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable=true

# Таймаути для RestTemplate (опціонально)
spring.mvc.async.request-timeout=10000